services:
  backend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
volumes:
  static:
